CREATE TABLE triage (
    SMALLINT_1 smallint,
    BOOLEAN boolean,
    UUID_1 uuid,
    HEX_8Char varchar(8),
    BIGINT_1_BYTES bigint,
    DOUBLE double precision,
    VARCHAR9 varchar(9),
    TIMESTAMPZ timestamptz,
    null varchar(4),
    EMPTYSTRING varchar(5),
    MONEY double precision,
    UUID_2_bad varchar(36),
    UUID_3 uuid,
    UUID_4 uuid,
    BIGINT_2 timestamptz,
    SMALLINT_2 smallint,
    INET inet,
    VARCHAR47 varchar(47),
    VARCHAR24 varchar(24),
    MACADDR macaddr,
    SMALLINT_3 smallint,
    SMALLINT_4 smallint,
    JSONB_1 jsonb,
    JSONB_2 jsonb
);