CREATE TABLE wf_jobs_m (
    _m_id varchar(8),
    _r_id varchar(32),
    _id smallint,
    _key uuid,
    _mtime timestamptz,
    image_uuid varchar(3),
    creator_uuid varchar(3),
    origin varchar(3),
    task varchar(3),
    workflow_uuid uuid,
    vm_uuid uuid,
    created_at timestamptz,
    exec_after timestamptz,
    runner_id uuid,
    target varchar(51),
    name varchar(25),
    taskId varchar(8),
    started timestamptz,
    elapsed double precision,
    endpoint varchar(129),
    serverUuids varchar(3),
    package jsonb,
    image jsonb,
    params jsonb,
    chain jsonb,
    chain_results jsonb,
    onerror jsonb,
    onerror_results jsonb
);